<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/auth.php';

require_role(['admin', 'accountant']);
$user = current_user();
$page_title = "Financial Reports — Digital Smart Class";

require_once __DIR__ . '/../includes/header.php';
?>

<div class="dashboard-layout">
    <aside class="sidebar">
        <div class="sidebar-user">
            <div class="sidebar-user-avatar" style="background: var(--dark-surface);"><i class="fas fa-user-shield"></i></div>
            <div class="sidebar-user-info">
                <h5><?= e($user['full_name']); ?></h5>
                <span><?= e(ucfirst($user['role'])); ?></span>
            </div>
        </div>
        <ul class="sidebar-menu">
            <li class="sidebar-item"><a href="<?= site_url('admin/dashboard.php'); ?>"><i class="fas fa-chart-pie"></i> Admin Overview</a></li>
            <li class="sidebar-item"><a href="<?= site_url('admin/users.php'); ?>"><i class="fas fa-users-cog"></i> Manage Users</a></li>
            <li class="sidebar-item"><a href="<?= site_url('admin/courses.php'); ?>"><i class="fas fa-graduation-cap"></i> Manage Courses</a></li>
            <li class="sidebar-item"><a href="<?= site_url('admin/payments.php'); ?>"><i class="fas fa-money-check-alt"></i> Payments Verification</a></li>
            <li class="sidebar-item active"><a href="<?= site_url('admin/reports.php'); ?>"><i class="fas fa-file-invoice-dollar"></i> Financial Reports</a></li>
        </ul>
    </aside>

    <main class="dashboard-main">
        <div class="dashboard-title-bar">
            <div>
                <h2>Revenue & Enrollment Reports</h2>
                <p style="color: var(--gray-500); font-size: 0.95rem;">Tuition analytics, payment gateway shares, and learner conversion rates.</p>
            </div>
            <button onclick="window.print()" class="btn btn-outline btn-sm">
                <i class="fas fa-print"></i> Print Report
            </button>
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-card-title">Gross Revenue (MTN MoMo)</div>
                <div class="stat-card-value" style="color: #ca8a04;">820,000 RWF</div>
            </div>
            <div class="stat-card">
                <div class="stat-card-title">Gross Revenue (Airtel)</div>
                <div class="stat-card-value" style="color: #dc2626;">240,000 RWF</div>
            </div>
            <div class="stat-card">
                <div class="stat-card-title">Bank Deposits (BK)</div>
                <div class="stat-card-value" style="color: #2563eb;">180,000 RWF</div>
            </div>
            <div class="stat-card">
                <div class="stat-card-title">Total Processed</div>
                <div class="stat-card-value" style="color: var(--success);">1,240,000 RWF</div>
            </div>
        </div>

        <div class="table-card">
            <div class="table-card-header">
                <h3 style="font-size: 1.15rem; font-weight: 700;">Revenue Generated By Course</h3>
            </div>
            <div class="table-responsive">
                <table>
                    <thead>
                        <tr>
                            <th>Course Name</th>
                            <th>Enrolled Students</th>
                            <th>Tuition Fee</th>
                            <th>Total Earned (RWF)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="font-weight: 700;">YouTube Creator Academy: From Absolute Beginner to Confident Creator</td>
                            <td>24 Paid</td>
                            <td>30,000 RWF</td>
                            <td style="font-weight: 700; color: var(--success);">720,000 RWF</td>
                        </tr>
                        <tr>
                            <td style="font-weight: 700;">Viral YouTube Shorts Engine: Idea, Script, Edit & 1M+ Views</td>
                            <td>12 Paid</td>
                            <td>30,000 RWF</td>
                            <td style="font-weight: 700; color: var(--success);">360,000 RWF</td>
                        </tr>
                        <tr>
                            <td style="font-weight: 700;">AI-Powered Long-Form Video Mastery: Automated Production & Monetization</td>
                            <td>4 Paid</td>
                            <td>40,000 RWF</td>
                            <td style="font-weight: 700; color: var(--success);">160,000 RWF</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
